export { default as Categories } from "./Categories";
export { default as DownloadApp } from "./DownloadApp";
export { default as Footer } from "./Footer";
export { default as Navbar } from "./Navbar";
export { default as Sidebar } from "./Sidebar";
export { default as Home } from "./Home";
export { default as Products } from "./Products";
export { default as GetApp } from "./GetApp";
export { default as SingleProduct } from "./SingleProduct";
